server:
  port: 9100
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: Paramecium88.
    hikari:
      minimum-idle: 10
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    servlet:
      load-on-startup: 1

File:
  uploadPath: ${user.dir}/upload

mybatis:
  configuration:
    map-underscore-to-camel-case: true